defmodule Infigonia.Infigonia.CurrencyRates do
  use Ecto.Schema

  embedded_schema do
    field :aed, :float
    field :afn, :float
    field :all, :float
    field :amd, :float
    field :ang, :float
    field :aoa, :float
    field :ars, :float
    field :aud, :float
    field :awg, :float
    field :azn, :float
    field :bam, :float
    field :bbd, :float
    field :bdt, :float
    field :bgn, :float
    field :bhd, :float
    field :bif, :float
    field :bmd, :float
    field :bnd, :float
    field :bob, :float
    field :brl, :float
    field :bsd, :float
    field :btc, :float
    field :btn, :float
    field :bwp, :float
    field :byn, :float
    field :byr, :float
    field :bzd, :float
    field :cad, :float
    field :cdf, :float
    field :chf, :float
    field :clf, :float
    field :clp, :float
    field :cny, :float
    field :cop, :float
    field :crc, :float
    field :cuc, :float
    field :cup, :float
    field :cve, :float
    field :czk, :float
    field :djf, :float
    field :dkk, :float
    field :dop, :float
    field :dzd, :float
    field :egp, :float
    field :ern, :float
    field :etb, :float
    field :eur, :float
    field :fjd, :float
    field :fkp, :float
    field :gbp, :float
    field :gel, :float
    field :ggp, :float
    field :ghs, :float
    field :gip, :float
    field :gmd, :float
    field :gnf, :float
    field :gtq, :float
    field :gyd, :float
    field :hkd, :float
    field :hnl, :float
    field :hrk, :float
    field :htg, :float
    field :huf, :float
    field :idr, :float
    field :ils, :float
    field :imp, :float
    field :inr, :float
    field :iqd, :float
    field :irr, :float
    field :isk, :float
    field :jep, :float
    field :jmd, :float
    field :jod, :float
    field :jpy, :float
    field :kes, :float
    field :kgs, :float
    field :khr, :float
    field :kmf, :float
    field :kpw, :float
    field :krw, :float
    field :kwd, :float
    field :kyd, :float
    field :kzt, :float
    field :lak, :float
    field :lbp, :float
    field :lkr, :float
    field :lrd, :float
    field :lsl, :float
    field :ltl, :float
    field :lvl, :float
    field :lyd, :float
    field :mad, :float
    field :mdl, :float
    field :mga, :float
    field :mkd, :float
    field :mmk, :float
    field :mnt, :float
    field :mop, :float
    field :mro, :float
    field :mur, :float
    field :mvr, :float
    field :mwk, :float
    field :mxn, :float
    field :myr, :float
    field :mzn, :float
    field :nad, :float
    field :ngn, :float
    field :nio, :float
    field :nok, :float
    field :npr, :float
    field :nzd, :float
    field :omr, :float
    field :pab, :float
    field :pen, :float
    field :pgk, :float
    field :php, :float
    field :pkr, :float
    field :pln, :float
    field :pyg, :float
    field :qar, :float
    field :ron, :float
    field :rsd, :float
    field :rub, :float
    field :rwf, :float
    field :sar, :float
    field :sbd, :float
    field :scr, :float
    field :sdg, :float
    field :sek, :float
    field :sgd, :float
    field :shp, :float
    field :sll, :float
    field :sos, :float
    field :srd, :float
    field :std, :float
    field :svc, :float
    field :syp, :float
    field :szl, :float
    field :thb, :float
    field :tjs, :float
    field :tmt, :float
    field :tnd, :float
    field :top, :float
    field :try, :float
    field :ttd, :float
    field :twd, :float
    field :tzs, :float
    field :uah, :float
    field :ugx, :float
    field :usd, :float
    field :uyu, :float
    field :uzs, :float
    field :vef, :float
    field :vnd, :float
    field :vuv, :float
    field :wst, :float
    field :xaf, :float
    field :xag, :float
    field :xau, :float
    field :xcd, :float
    field :xdr, :float
    field :xof, :float
    field :xpf, :float
    field :yer, :float
    field :zar, :float
    field :zmk, :float
    field :zmw, :float
    field :zwl, :float
  end
end
